### ISSUE TITLE
Can't add Hue Tap Switch via Indigo New | Hue Lights | Hue Tap Switch

### ISSUE THREAD

**Issue by ellipsis-instruments** [kw123/Hue-Lights-Indigo-plugin#21]
Hello, I'm trying to connect two Hue Tap Switches in Indigo (they are already registered with the Hue Bridge), but the plugin doesn't show that any are available. The switches are seen, however, as sensors by the plugin. Here's one of them printed to the log:

Dec 27, 2022 at 12:36:28 PM
   Hue Lights                      printHueData --- sensors: hub:0, sensorId=11: Hue-Dict
{
  "capabilities": {
    "certified": true,
    "inputs": [
      {
        "events": [
          {
            "buttonevent": 34,
            "eventtype": "initial_press"
          }
        ],
        "repeatintervals": []
      },
      {
        "events": [
          {
            "buttonevent": 16,
            "eventtype": "initial_press"
          }
        ],
        "repeatintervals": []
      },
      {
        "events": [
          {
            "buttonevent": 17,
            "eventtype": "initial_press"
          }
        ],
        "repeatintervals": []
      },
      {
        "events": [
          {
            "buttonevent": 18,
            "eventtype": "initial_press"
          }
        ],
        "repeatintervals": []
      }
    ],
    "primary": true
  },
  "config": {
    "on": true
  },
  "diversityid": "d8cde5d5-0eef-4b95-b0f0-71ddd2952af4",
  "manufacturername": "Signify Netherlands B.V.",
  "modelid": "ZGPSWITCH",
  "name": "Hue tap switch Iveta",
  "productname": "Hue tap switch",
  "state": {
    "buttonevent": 17,
    "lastupdated": "2022-12-27T10:28:15"
  },
  "swupdate": {
    "lastinstall": null,
    "state": "notupdatable"
  },
  "type": "ZGPSwitch",
  "uniqueid": "00:00:00:00:00:46:30:ee-f2"
} 

I'll note that these switches had been installed as Indigo Devices, then deleted, after deleting/reinstalling/renaming them with the Hue Bridge

**Comment by kw123** [comment]
Try menu: add devices ..That will generate all available lights, sensors, groups in indigo. KarlOn 27.12.2022, at 11:40, ellipsis instruments ***@***.***> wrote:﻿
Hello, I'm trying to connect two Hue Tap Switches in Indigo (they are already registered with the Hue Bridge), but the plugin doesn't show that any are available. The switches are seen, however, as sensors by the plugin. Here's one of them printed to the log:
Dec 27, 2022 at 12:36:28 PM
Hue Lights                      printHueData --- sensors: hub:0, sensorId=11: Hue-Dict
{
"capabilities": {
"certified": true,
"inputs": [
{
"events": [
{
"buttonevent": 34,
"eventtype": "initial_press"
}
],
"repeatintervals": []
},
{
"events": [
{
"buttonevent": 16,
"eventtype": "initial_press"
}
],
"repeatintervals": []
},
{
"events": [
{
"buttonevent": 17,
"eventtype": "initial_press"
}
],
"repeatintervals": []
},
{
"events": [
{
"buttonevent": 18,
"eventtype": "initial_press"
}
],
"repeatintervals": []
}
],
"primary": true
},
"config": {
"on": true
},
"diversityid": "d8cde5d5-0eef-4b95-b0f0-71ddd2952af4",
"manufacturername": "Signify Netherlands B.V.",
"modelid": "ZGPSWITCH",
"name": "Hue tap switch Iveta",
"productname": "Hue tap switch",
"state": {
"buttonevent": 17,
"lastupdated": "2022-12-27T10:28:15"
},
"swupdate": {
"lastinstall": null,
"state": "notupdatable"
},
"type": "ZGPSwitch",
"uniqueid": "00:00:00:00:00:46:30:ee-f2"
}
I'll note that these switches had been installed as Indigo Devices, then deleted, after deleting/reinstalling/renaming them with the Hue Bridge

**Comment by kw123** [comment]
Also do a Menu: Print All lights  etc. check if it is not already somewhere in an indigo folder. KarlOn 27.12.2022, at 12:09, karl wachs ***@***.***> wrote:﻿Try menu: add devices ..That will generate all available lights, sensors, groups in indigo. KarlOn 27.12.2022, at 11:40, ellipsis instruments ***@***.***> wrote:﻿
Hello, I'm trying to connect two Hue Tap Switches in Indigo (they are already registered with the Hue Bridge), but the plugin doesn't show that any are available. The switches are seen, however, as sensors by the plugin. Here's one of them printed to the log:
Dec 27, 2022 at 12:36:28 PM
Hue Lights                      printHueData --- sensors: hub:0, sensorId=11: Hue-Dict
{
"capabilities": {
"certified": true,
"inputs": [
{
"events": [
{
"buttonevent": 34,
"eventtype": "initial_press"
}
],
"repeatintervals": []
},
{
"events": [
{
"buttonevent": 16,
"eventtype": "initial_press"
}
],
"repeatintervals": []
},
{
"events": [
{
"buttonevent": 17,
"eventtype": "initial_press"
}
],
"repeatintervals": []
},
{
"events": [
{
"buttonevent": 18,
"eventtype": "initial_press"
}
],
"repeatintervals": []
}
],
"primary": true
},
"config": {
"on": true
},
"diversityid": "d8cde5d5-0eef-4b95-b0f0-71ddd2952af4",
"manufacturername": "Signify Netherlands B.V.",
"modelid": "ZGPSWITCH",
"name": "Hue tap switch Iveta",
"productname": "Hue tap switch",
"state": {
"buttonevent": 17,
"lastupdated": "2022-12-27T10:28:15"
},
"swupdate": {
"lastinstall": null,
"state": "notupdatable"
},
"type": "ZGPSwitch",
"uniqueid": "00:00:00:00:00:46:30:ee-f2"
}
I'll note that these switches had been installed as Indigo Devices, then deleted, after deleting/reinstalling/renaming them with the Hue Bridge

**Comment by ellipsis-instruments** [comment]
Add devices (sensors) did the trick, thank you
