### ISSUE TITLE
Github catchup

### ISSUE THREAD

**Issue by indigo-jay** [kw123/Hue-Lights-Indigo-plugin#8]
This is just a reminder issue that we need to move previous releases from direct plugin store upload to releases here, get the code caught up, and institute the new fork/pr/merge process for this repo.

Will have to wait until after we get 2022.1 out.

**Comment by kw123** [comment]
Jay,

I know i should be able to do this, but i tried for an hour to get the guithub replication working .. i hate to read manuals.  but i will try again.

Karl

**Comment by indigo-jay** [comment]
Please don't worry about it right now - until I can get to it lets just keep going with the current process. In all honesty, I'd highly recommend just leaving this plugin alone until after we release 2022.1. You have all of your other plugins to worry about. Up to you of course.

**Comment by kw123** [comment]
Jay
I had to fix bugs.  
There is one more change I need to make.  
Nathan included the request library in the plugin. I need to change that. 

And yes I will be starting with my other plugins. 


Karl Wachs

**Comment by indigo-jay** [comment]
I'm closing this bug as I got the repo cleaned up and transferred to Karl for continued development.
